import { Standing, Team1 } from '@/types';
import 'server-only';
import getStandings from './getStandings1';

export default async function getTeams(): Promise<Team1[]> {

    try {


        const teams: Team1[]  = [
  { country: "BE", name: "Belgium", id: 1 },
  { country: "FR", name: "France", id: 2 },
  { country: "HR", name: "Croatia", id: 3 },
  { country: "RU", name: "Russia", id: 4 },
  { country: "SE", name: "Sweden", id: 5 },
  { country: "BR", name: "Brazil", id: 6 },
  { country: "UY", name: "Uruguay", id: 7 },
  { country: "CO", name: "Colombia", id: 8 },
  { country: "ES", name: "Spain", id: 9 },
  { country: "GB-ENG", name: "England", id: 10 },
  { country: "PA", name: "Panama", id: 11 },
  { country: "JP", name: "Japan", id: 12 },
  { country: "SN", name: "Senegal", id: 13 },
  { country: "RS", name: "Serbia", id: 14 },
  { country: "CH", name: "Switzerland", id: 15 },
  { country: "MX", name: "Mexico", id: 16 },
  { country: "KR", name: "South Korea", id: 17 },
  { country: "IS", name: "Iceland", id: 18 },
  { country: "NG", name: "Nigeria", id: 19 },
  { country: "AU", name: "Australia", id: 20 },
  { country: "DK", name: "Denmark", id: 21 },
  { country: "IR", name: "Iran", id: 22 },
  { country: "SA", name: "Saudi Arabia", id: 23 },
  { country: "PL", name: "Poland", id: 24 },
  { country: "DE", name: "Germany", id: 25 },
  { country: "AR", name: "Argentina", id: 26 },
  { country: "PT", name: "Portugal", id: 27 },
  { country: "TN", name: "Tunisia", id: 28 },
  { country: "CR", name: "Costa Rica", id: 29 },
  { country: "PE", name: "Peru", id: 30 },
  { country: "MA", name: "Morocco", id: 31 },
  { country: "EG", name: "Egypt", id: 32 },
  { country: "GB-ENG", name: "Manchester United", id: 33 },
  { country: "GB-ENG", name: "Newcastle", id: 34 },
  { country: "GB-ENG", name: "Bournemouth", id: 35 },
  { country: "GB-ENG", name: "Fulham", id: 36 },
  { country: "GB-ENG", name: "Huddersfield", id: 37 },
  { country: "GB-ENG", name: "Watford", id: 38 },
  { country: "GB-ENG", name: "Wolves", id: 39 },
  { country: "GB-ENG", name: "Liverpool", id: 40 },
  { country: "GB-ENG", name: "Southampton", id: 41 },
  { country: "GB-ENG", name: "Arsenal", id: 42 },
  { country: "GB-WLS", name: "Cardiff", id: 43 },
  { country: "GB-ENG", name: "Burnley", id: 44 },
  { country: "GB-ENG", name: "Everton", id: 45 },
  { country: "GB-ENG", name: "Leicester", id: 46 },
  { country: "GB-ENG", name: "Tottenham", id: 47 },
  { country: "GB-ENG", name: "West Ham", id: 48 },
  { country: "GB-ENG", name: "Chelsea", id: 49 },
  { country: "GB-ENG", name: "Manchester City", id: 50 },
  { country: "GB-ENG", name: "Brighton", id: 51 },
  { country: "GB-ENG", name: "Crystal Palace", id: 52 },
  { country: "GB-ENG", name: "Reading", id: 53 },
  { country: "GB-ENG", name: "Birmingham", id: 54 },
  { country: "GB-ENG", name: "Brentford", id: 55 },
  { country: "GB-ENG", name: "Bristol City", id: 56 },
  { country: "GB-ENG", name: "Ipswich", id: 57 },
  { country: "GB-ENG", name: "Millwall", id: 58 },
  { country: "GB-ENG", name: "Preston", id: 59 },
  { country: "GB-ENG", name: "West Brom", id: 60 },
  { country: "GB-ENG", name: "Wigan", id: 61 },
  { country: "GB-ENG", name: "Sheffield Utd", id: 62 },
  { country: "GB-ENG", name: "Leeds", id: 63 },
  { country: "GB-ENG", name: "Hull City", id: 64 },
  { country: "GB-ENG", name: "Nottingham Forest", id: 65 },
  { country: "GB-ENG", name: "Aston Villa", id: 66 },
  { country: "GB-ENG", name: "Blackburn", id: 67 },
  { country: "GB-ENG", name: "Bolton", id: 68 },
  { country: "GB-ENG", name: "Derby", id: 69 },
  { country: "GB-ENG", name: "Middlesbrough", id: 70 },
  { country: "GB-ENG", name: "Norwich", id: 71 },
  { country: "GB-ENG", name: "QPR", id: 72 },
  { country: "GB-ENG", name: "Rotherham", id: 73 },
  { country: "GB-ENG", name: "Sheffield Wednesday", id: 74 },
  { country: "GB-ENG", name: "Stoke City", id: 75 },
  { country: "GB-WLS", name: "Swansea", id: 76 },
  { country: "FR", name: "Angers", id: 77 },
  { country: "FR", name: "Bordeaux", id: 78 },
  { country: "FR", name: "Lille", id: 79 },
  { country: "FR", name: "Lyon", id: 80 },
  { country: "FR", name: "Marseille", id: 81 },
  { country: "FR", name: "Montpellier", id: 82 },
  { country: "FR", name: "Nantes", id: 83 },
  { country: "FR", name: "Nice", id: 84 },
  { country: "FR", name: "Paris Saint Germain", id: 85 },
  { country: "FR", name: "ST Etienne", id: 86 },
  { country: "FR", name: "Amiens", id: 87 },
  { country: "FR", name: "Caen", id: 88 },
  { country: "FR", name: "Dijon", id: 89 },
  { country: "FR", name: "Guingamp", id: 90 },
  { country: "FR", name: "Monaco", id: 91 },
  { country: "FR", name: "Nimes", id: 92 },
  { country: "FR", name: "Reims", id: 93 },
  { country: "FR", name: "Rennes", id: 94 },
  { country: "FR", name: "Strasbourg", id: 95 },
  { country: "FR", name: "Toulouse", id: 96 },
  { country: "FR", name: "Lorient", id: 97 },
  { country: "FR", name: "Ajaccio", id: 98 },
  { country: "FR", name: "Clermont Foot", id: 99 },
  { country: "FR", name: "Gazelec FC Ajaccio", id: 100 },
  { country: "FR", name: "Grenoble", id: 101 },
  { country: "FR", name: "Nancy", id: 102 },
  { country: "FR", name: "Orleans", id: 103 },
  { country: "FR", name: "RED Star FC 93", id: 104 },
  { country: "FR", name: "Valenciennes", id: 105 },
  { country: "FR", name: "Stade Brestois 29", id: 106 },
  { country: "FR", name: "Chateauroux", id: 107 },
  { country: "FR", name: "Auxerre", id: 108 },
  { country: "FR", name: "Beziers", id: 109 },
  { country: "FR", name: "Estac Troyes", id: 110 },
  { country: "FR", name: "Le Havre", id: 111 },
  { country: "FR", name: "Metz", id: 112 },
  { country: "FR", name: "Niort", id: 113 },
  { country: "FR", name: "Paris FC", id: 114 },
  { country: "FR", name: "Sochaux", id: 115 },
  { country: "FR", name: "Lens", id: 116 },
  { country: "BR", name: "Atletico Mineiro", id: 117 },
  { country: "BR", name: "Bahia", id: 118 },
  { country: "BR", name: "Internacional", id: 119 },
  { country: "BR", name: "Botafogo", id: 120 },
  { country: "BR", name: "Palmeiras", id: 121 },
  { country: "BR", name: "Parana", id: 122 },
  { country: "BR", name: "Sport Recife", id: 123 },
  { country: "BR", name: "Fluminense", id: 124 },
  { country: "BR", name: "America Mineiro", id: 125 },
  { country: "BR", name: "Sao Paulo", id: 126 },
  { country: "BR", name: "Flamengo", id: 127 },
  { country: "BR", name: "Santos", id: 128 },
  { country: "BR", name: "Ceara", id: 129 },
  { country: "BR", name: "Gremio", id: 130 },
  { country: "BR", name: "Corinthians", id: 131 },
  { country: "BR", name: "Chapecoense-sc", id: 132 },
  { country: "BR", name: "Vasco DA Gama", id: 133 },
  { country: "BR", name: "Atletico Paranaense", id: 134 },
  { country: "BR", name: "Cruzeiro", id: 135 },
  { country: "BR", name: "Vitoria", id: 136 },
  { country: "BR", name: "Figueirense", id: 137 },
  { country: "BR", name: "Guarani Campinas", id: 138 },
  { country: "BR", name: "Ponte Preta", id: 139 },
  { country: "BR", name: "Criciuma", id: 140 },
  { country: "BR", name: "Brasil DE Pelotas", id: 141 },
  { country: "BR", name: "Vila Nova", id: 142 },
  { country: "BR", name: "Oeste", id: 143 },
  { country: "BR", name: "Atletico Goianiense", id: 144 },
  { country: "BR", name: "Avai", id: 145 },
  { country: "BR", name: "CRB", id: 146 },
  { country: "BR", name: "Coritiba", id: 147 },
  { country: "BR", name: "Londrina", id: 148 },
  { country: "BR", name: "Paysandu", id: 149 },
  { country: "BR", name: "CSA", id: 150 },
  { country: "BR", name: "Goias", id: 151 },
  { country: "BR", name: "Juventude", id: 152 },
  { country: "BR", name: "BOA", id: 153 },
  { country: "BR", name: "Fortaleza EC", id: 154 },
  { country: "BR", name: "Sampaio Correa", id: 155 },
  { country: "BR", name: "Sao Bento", id: 156 },
  { country: "DE", name: "Bayern München", id: 157 },
  { country: "DE", name: "Fortuna Düsseldorf", id: 158 },
  { country: "DE", name: "Hertha BSC", id: 159 },
  { country: "DE", name: "SC Freiburg", id: 160 },
  { country: "DE", name: "VfL Wolfsburg", id: 161 },
  { country: "DE", name: "Werder Bremen", id: 162 },
  { country: "DE", name: "Borussia Mönchengladbach", id: 163 },
  { country: "DE", name: "FSV Mainz 05", id: 164 },
  { country: "DE", name: "Borussia Dortmund", id: 165 },
  { country: "DE", name: "Hannover 96", id: 166 },
  { country: "DE", name: "1899 Hoffenheim", id: 167 },
  { country: "DE", name: "Bayer Leverkusen", id: 168 },
  { country: "DE", name: "Eintracht Frankfurt", id: 169 },
  { country: "DE", name: "FC Augsburg", id: 170 },
  { country: "DE", name: "1. FC Nürnberg", id: 171 },
  { country: "DE", name: "VfB Stuttgart", id: 172 },
  { country: "DE", name: "RB Leipzig", id: 173 },
  { country: "DE", name: "FC Schalke 04", id: 174 },
  { country: "DE", name: "Hamburger SV", id: 175 },
  { country: "DE", name: "VfL Bochum", id: 176 },
  { country: "DE", name: "SSV Jahn Regensburg", id: 177 },
  { country: "DE", name: "SpVgg Greuther Fürth", id: 178 },
  { country: "DE", name: "1. FC Magdeburg", id: 179 },
  { country: "DE", name: "1. FC Heidenheim", id: 180 },
  { country: "DE", name: "SV Darmstadt 98", id: 181 },
  { country: "DE", name: "Union Berlin", id: 182 },
  { country: "DE", name: "Dynamo Dresden", id: 183 },
  { country: "DE", name: "FC Ingolstadt 04", id: 184 },
  { country: "DE", name: "SC Paderborn 07", id: 185 },
  { country: "DE", name: "FC St. Pauli", id: 186 },
  { country: "DE", name: "MSV Duisburg", id: 187 },
  { country: "DE", name: "Arminia Bielefeld", id: 188 },
  { country: "DE", name: "SV Sandhausen", id: 189 },
  { country: "DE", name: "Erzgebirge Aue", id: 190 },
  { country: "DE", name: "Holstein Kiel", id: 191 },
  { country: "DE", name: "1.FC Köln", id: 192 },
  { country: "NL", name: "PEC Zwolle", id: 193 },
  { country: "NL", name: "Ajax", id: 194 },
  { country: "NL", name: "Willem II", id: 195 },
  { country: "NL", name: "Excelsior", id: 196 },
  { country: "NL", name: "PSV Eindhoven", id: 197 },
  { country: "NL", name: "ADO Den Haag", id: 198 },
  { country: "NL", name: "De Graafschap", id: 199 },
  { country: "NL", name: "Vitesse", id: 200 },
  { country: "NL", name: "AZ Alkmaar", id: 201 },
  { country: "NL", name: "Groningen", id: 202 },
  { country: "NL", name: "NAC Breda", id: 203 },
  { country: "NL", name: "VVV Venlo", id: 204 },
  { country: "NL", name: "Fortuna Sittard", id: 205 },
  { country: "NL", name: "Heracles", id: 206 },
  { country: "NL", name: "Utrecht", id: 207 },
  { country: "NL", name: "Emmen", id: 208 },
  { country: "NL", name: "Feyenoord", id: 209 },
  { country: "NL", name: "Heerenveen", id: 210 },
  { country: "PT", name: "Benfica", id: 211 },
  { country: "PT", name: "FC Porto", id: 212 },
  { country: "PT", name: "Feirense", id: 213 },
  { country: "PT", name: "Maritimo", id: 214 },
  { country: "PT", name: "Moreirense", id: 215 },
  { country: "PT", name: "Portimonense", id: 216 },
  { country: "PT", name: "SC Braga", id: 217 },
  { country: "PT", name: "Tondela", id: 218 },
  { country: "PT", name: "Vitoria Setubal", id: 219 },
  { country: "PT", name: "Aves", id: 220 },
  { country: "PT", name: "Belenenses", id: 221 },
  { country: "PT", name: "Boavista", id: 222 },
  { country: "PT", name: "Chaves", id: 223 },
  { country: "PT", name: "Guimaraes", id: 224 },
  { country: "PT", name: "Nacional", id: 225 },
  { country: "PT", name: "Rio Ave", id: 226 },
  { country: "PT", name: "Santa Clara", id: 227 },
  { country: "PT", name: "Sporting CP", id: 228 },
  { country: "PT", name: "Benfica B", id: 229 },
  { country: "PT", name: "Estoril", id: 230 },
  { country: "PT", name: "Farense", id: 231 },
  { country: "PT", name: "Guimaraes B", id: 232 },
  { country: "PT", name: "Oliveirense", id: 233 },
  { country: "PT", name: "Pacos Ferreira", id: 234 },
  { country: "PT", name: "Penafiel", id: 235 },
  { country: "PT", name: "SC Covilha", id: 236 },
  { country: "PT", name: "Varzim", id: 237 },
  { country: "PT", name: "Academico Viseu", id: 238 },
  { country: "PT", name: "Academica", id: 239 },
  { country: "PT", name: "Arouca", id: 240 },
  { country: "PT", name: "Cova De Piedade", id: 241 },
  { country: "PT", name: "Famalicao", id: 242 },
  { country: "PT", name: "FC Porto B", id: 243 },
  { country: "PT", name: "Leixoes", id: 244 },
  { country: "PT", name: "Mafra", id: 245 },
  { country: "PT", name: "SC Braga B", id: 246 },
  { country: "GB-SCT", name: "Celtic", id: 247 },
  { country: "GB-SCT", name: "Hamilton Academical", id: 248 },
  { country: "GB-SCT", name: "Hibernian", id: 249 },
  { country: "GB-SCT", name: "Kilmarnock", id: 250 },
  { country: "GB-SCT", name: "ST Mirren", id: 251 },
  { country: "GB-SCT", name: "Aberdeen", id: 252 },
  { country: "GB-SCT", name: "Dundee", id: 253 },
  { country: "GB-SCT", name: "Heart Of Midlothian", id: 254 },
  { country: "GB-SCT", name: "Livingston", id: 255 },
  { country: "GB-SCT", name: "Motherwell", id: 256 },
  { country: "GB-SCT", name: "Rangers", id: 257 },
  { country: "GB-SCT", name: "ST Johnstone", id: 258 },
  { country: "BE", name: "Lommel United", id: 259 },
  { country: "BE", name: "OH Leuven", id: 260 },
  { country: "BE", name: "KVC Westerlo", id: 261 },
  { country: "BE", name: "Tubize", id: 262 },
  { country: "BE", name: "Beerschot Wilrijk", id: 263 },
  { country: "BE", name: "Roeselare", id: 264 },
  { country: "BE", name: "Union S.gilloise", id: 265 },
  { country: "BE", name: "KV Mechelen", id: 266 },
  { country: "IS", name: "Fylkir", id: 267 },
  { country: "IS", name: "IBV Vestmannaeyjar", id: 268 },
  { country: "IS", name: "Keflavik", id: 269 },
  { country: "IS", name: "FH hafnarfjordur", id: 270 },
  { country: "IS", name: "KR Reykjavik", id: 271 },
  { country: "IS", name: "KA Akureyri", id: 272 },
  { country: "IS", name: "Fjolnir", id: 273 },
  { country: "IS", name: "Valur Reykjavik", id: 274 },
  { country: "IS", name: "Stjarnan", id: 275 },
  { country: "IS", name: "Breidablik", id: 276 },
  { country: "IS", name: "Grindavik", id: 277 },
  { country: "IS", name: "Vikingur Reykjavik", id: 278 },
  { country: "JP", name: "Consadole Sapporo", id: 279 },
  { country: "JP", name: "Jubilo Iwata", id: 280 },
  { country: "JP", name: "Kashiwa Reysol", id: 281 },
  { country: "JP", name: "Sanfrecce Hiroshima", id: 282 },
  { country: "JP", name: "Shimizu S-pulse", id: 283 },
  { country: "JP", name: "Shonan Bellmare", id: 284 },
  { country: "JP", name: "V-varen Nagasaki", id: 285 },
  { country: "JP", name: "Vegalta Sendai", id: 286 },
  { country: "JP", name: "Urawa", id: 287 },
  { country: "JP", name: "Nagoya Grampus", id: 288 },
  { country: "JP", name: "Vissel Kobe", id: 289 },
  { country: "JP", name: "Kashima", id: 290 },
  { country: "JP", name: "Cerezo Osaka", id: 291 },
  { country: "JP", name: "FC Tokyo", id: 292 },
  { country: "JP", name: "Gamba Osaka", id: 293 },
  { country: "JP", name: "Kawasaki Frontale", id: 294 },
  { country: "JP", name: "Sagan Tosu", id: 295 },
  { country: "JP", name: "Yokohama F. Marinos", id: 296 },
  { country: "JP", name: "FC Gifu", id: 297 },
  { country: "JP", name: "Oita Trinita", id: 298 },
  { country: "JP", name: "Tokushima Vortis", id: 299 },
  { country: "JP", name: "Kanazawa", id: 300 },
   { country: "JP", name: "JEF United Chiba", id: 301 },
  { country: "JP", name: "Kyoto Sanga", id: 302 },
  { country: "JP", name: "Machida Zelvia", id: 303 },
  { country: "JP", name: "Matsumoto Yamaga", id: 304 },
  { country: "JP", name: "Mito Hollyhock", id: 305 },
  { country: "JP", name: "Tokyo Verdy", id: 306 },
  { country: "JP", name: "Yokohama FC", id: 307 },
  { country: "JP", name: "Ventforet Kofu", id: 308 },
  { country: "JP", name: "Renofa Yamaguchi", id: 309 },
  { country: "JP", name: "Fagiano Okayama", id: 310 },
  { country: "JP", name: "Albirex Niigata", id: 311 },
  { country: "JP", name: "Montedio Yamagata", id: 312 },
  { country: "JP", name: "Omiya Ardija", id: 313 },
  { country: "JP", name: "Roasso Kumamoto", id: 314 },
  { country: "JP", name: "Tochigi SC", id: 315 },
  { country: "JP", name: "Avispa Fukuoka", id: 316 },
  { country: "JP", name: "Kamatamare Sanuki", id: 317 },
  { country: "JP", name: "Ehime FC", id: 318 },
  { country: "NO", name: "Brann", id: 319 },
  { country: "NO", name: "Kristiansund BK", id: 320 },
  { country: "NO", name: "Lillestrom", id: 321 },
  { country: "NO", name: "Ranheim", id: 322 },
  { country: "NO", name: "Stabaek", id: 323 },
  { country: "NO", name: "Stromsgodset", id: 324 },
  { country: "NO", name: "Tromso", id: 325 },
  { country: "NO", name: "Valerenga", id: 326 },
  { country: "NO", name: "Bodo/Glimt", id: 327 },
  { country: "NO", name: "Haugesund", id: 328 },
  { country: "NO", name: "Molde", id: 329 },
  { country: "NO", name: "ODD Ballklubb", id: 330 },
  { country: "NO", name: "Rosenborg", id: 331 },
  { country: "NO", name: "Sandefjord", id: 332 },
  { country: "NO", name: "Sarpsborg 08 FF", id: 333 },
  { country: "NO", name: "Start", id: 334 },
  { country: "PL", name: "Miedz Legnica", id: 335 },
  { country: "PL", name: "Jagiellonia", id: 336 },
  { country: "PL", name: "Slask Wroclaw", id: 337 },
  { country: "PL", name: "Wisla Krakow", id: 338 },
  { country: "PL", name: "Legia Warszawa", id: 339 },
  { country: "PL", name: "Gornik Zabrze", id: 340 },
  { country: "PL", name: "Wisla Plock", id: 341 },
  { country: "PL", name: "Zaglebie Sosnowiec", id: 342 },
  { country: "PL", name: "Lechia Gdansk", id: 343 },
  { country: "PL", name: "Arka Gdynia", id: 344 },
  { country: "PL", name: "Zaglebie Lubin", id: 345 },
  { country: "PL", name: "Korona Kielce", id: 346 },
  { country: "PL", name: "Lech Poznan", id: 347 },
  { country: "PL", name: "Pogon Szczecin", id: 348 },
  { country: "PL", name: "Piast Gliwice", id: 349 },
  { country: "PL", name: "Cracovia Krakow", id: 350 },
  { country: "GB-WLS", name: "Aberystwyth Town", id: 351 },
  { country: "GB-WLS", name: "Bala Town", id: 352 },
  { country: "GB-WLS", name: "Cardiff MET", id: 353 },
  { country: "GB-WLS", name: "The New Saints", id: 354 },
  { country: "GB-WLS", name: "llanelli AFC", id: 355 },
  { country: "GB-WLS", name: "Caernarfon Town", id: 356 },
  { country: "GB-WLS", name: "GAP Connah S Quay FC", id: 357 },
  { country: "GB-WLS", name: "Newtown AFC", id: 358 },
  { country: "GB-WLS", name: "Carmarthen Town", id: 359 },
  { country: "GB-WLS", name: "Cefn Druids AFC", id: 360 },
  { country: "GB-WLS", name: "Barry Town", id: 361 },
  { country: "GB-WLS", name: "Llandudno", id: 362 },
  { country: "SE", name: "Hammarby FF", id: 363 },
  { country: "SE", name: "Djurgardens IF", id: 364 },
  { country: "SE", name: "Orebro SK", id: 365 },
  { country: "SE", name: "IFK Goteborg", id: 366 },
  { country: "SE", name: "BK Hacken", id: 367 },
  { country: "SE", name: "dalkurd FF", id: 368 },
  { country: "SE", name: "trelleborgs FF", id: 369 },
  { country: "SE", name: "Sirius", id: 370 },
  { country: "SE", name: "IF Brommapojkarna", id: 371 },
  { country: "SE", name: "IF Elfsborg", id: 372 },
  { country: "SE", name: "GIF Sundsvall", id: 373 },
  { country: "SE", name: "Kalmar FF", id: 374 },
  { country: "SE", name: "Malmo FF", id: 375 },
  { country: "SE", name: "Ostersunds FK", id: 376 },
  { country: "SE", name: "AIK Stockholm", id: 377 },
  { country: "SE", name: "IFK Norrkoping", id: 378 },
  { country: "BY", name: "FC Slutsk", id: 379 },
  { country: "BY", name: "FC Minsk", id: 380 },
  { country: "BY", name: "Smolevichi-Sti", id: 381 },
  { country: "BY", name: "FC Vitebsk", id: 382 },
  { country: "BY", name: "Torpedo Minsk", id: 383 },
  { country: "BY", name: "FC Dnepr Mogilev", id: 384 },
  { country: "BY", name: "Torpedo Zhodino", id: 385 },
  { country: "BY", name: "Dinamo Brest", id: 386 },
  { country: "BY", name: "Neman", id: 387 },
  { country: "BY", name: "Bate Borisov", id: 388 },
  { country: "BY", name: "FC Gomel", id: 389 },
  { country: "BY", name: "Gorodeya", id: 390 },
  { country: "BY", name: "FC Isloch Minsk R.", id: 391 },
  { country: "BY", name: "Shakhter Soligorsk", id: 392 },
  { country: "BY", name: "Fc Luch Minsk", id: 393 },
  { country: "BY", name: "Dinamo Minsk", id: 394 },
  { country: "DK", name: "Vejle", id: 395 },
  { country: "DK", name: "Sonderjyske", id: 396 },
  { country: "DK", name: "FC Midtjylland", id: 397 },
  { country: "DK", name: "FC Nordsjaelland", id: 398 },
  { country: "DK", name: "Vendsyssel FF", id: 399 },
  { country: "DK", name: "FC Copenhagen", id: 400 },
  { country: "DK Denmark", name: "Randers FC", id: 401 },
  { country: "DK Denmark", name: "Aalborg", id: 402 },
  { country: "DK Denmark", name: "Esbjerg", id: 403 },
  { country: "DK Denmark", name: "AC Horsens", id: 404 },
  { country: "DK Denmark", name: "Odense", id: 405 },
  { country: "DK Denmark", name: "Aarhus", id: 406 },
  { country: "DK Denmark", name: "Brondby Brondby", id: 407 },
  { country: "DK Denmark", name: "Hobro", id: 408 },
  { country: "NL Netherlands", name: "Dordrecht", id: 409 },
  { country: "NL Netherlands", name: "GO Ahead Eagles GO Ahead Eagles", id: 410 },
  { country: "NL Netherlands", name: "Jong PSV Jong PSV", id: 411 },
  { country: "NL Netherlands", name: "MVV", id: 412 },
  { country: "NL Netherlands", name: "NEC Nijmegen", id: 413 },
  { country: "NL Netherlands", name: "Roda", id: 414 },
  { country: "NL Netherlands", name: "Twente", id: 415 },
  { country: "NL Netherlands", name: "FC Volendam", id: 416 },
  { country: "NL Netherlands", name: "Waalwijk Waalwijk", id: 417 },
  { country: "NL Netherlands", name: "Jong AZ Jong AZ", id: 418 },
  { country: "NL Netherlands", name: "Almere City FC", id: 419 },
  { country: "NL Netherlands", name: "Cambuur Cambuur", id: 420 },
  { country: "NL Netherlands", name: "Den Bosch", id: 421 },
  { country: "NL Netherlands", name: "FC Eindhoven", id: 422 },
  { country: "NL Netherlands", name: "FC OSS FC OSS", id: 423 },
  { country: "NL Netherlands", name: "Helmond Sport", id: 424 },
  { country: "NL Netherlands", name: "Jong Ajax", id: 425 },
  { country: "NL Netherlands", name: "Sparta Rotterdam Sparta Rotterdam", id: 426 },
  { country: "NL Netherlands", name: "Telstar", id: 427 },
  { country: "NL Netherlands", name: "Jong Utrecht", id: 428 },
  { country: "FR France", name: "Bourg-en-bresse 01", id: 430 },
  { country: "FR France", name: "Quevilly Quevilly", id: 431 },
  { country: "FR France", name: "Tours Tours", id: 432 },
  { country: "FR France", name: "Laval", id: 433 },
  { country: "AR Argentina", name: "Gimnasia L.P.", id: 434 },
  { country: "AR Argentina", name: "River Plate", id: 435 },
  { country: "AR Argentina", name: "Racing Club", id: 436 },
  { country: "AR Argentina", name: "Rosario Central", id: 437 },
  { country: "AR Argentina", name: "Velez Sarsfield", id: 438 },
  { country: "AR Argentina", name: "Godoy Cruz", id: 439 },
  { country: "AR Argentina", name: "Belgrano Cordoba Belgrano Cordoba", id: 440 },
  { country: "AR Argentina", name: "Union Santa Fe Union Santa Fe", id: 441 },
  { country: "AR Argentina", name: "Defensa Y Justicia", id: 442 },
  { country: "AR Argentina", name: "Olimpo Bahia Blanca", id: 443 },
  { country: "AR Argentina", name: "Patronato Patronato", id: 444 },
  { country: "AR Argentina", name: "Huracan", id: 445 },
  { country: "AR Argentina", name: "Lanus Lanus", id: 446 },
  { country: "AR Argentina", name: "Chacarita Juniors Chacarita Juniors", id: 447 },
  { country: "AR Argentina", name: "Colon Santa Fe Colon Santa Fe", id: 448 },
  { country: "AR Argentina", name: "Banfield Banfield", id: 449 },
  { country: "AR Argentina", name: "Estudiantes L.P.", id: 450 },
  { country: "AR Argentina", name: "Boca Juniors Boca Juniors", id: 451 },
  { country: "AR Argentina", name: "Tigre Tigre", id: 452 },
  { country: "AR Argentina", name: "Independiente Independiente", id: 453 },
  { country: "AR Argentina", name: "Temperley Temperley", id: 454 },
  { country: "AR Argentina", name: "Atletico Tucuman Atletico Tucuman", id: 455 },
  { country: "AR Argentina", name: "Talleres Cordoba Talleres Cordoba", id: 456 },
  { country: "AR Argentina", name: "Newells Old Boys Newells Old Boys", id: 457 },
  { country: "AR Argentina", name: "Argentinos JRS Argentinos JRS", id: 458 },
  { country: "AR Argentina", name: "Arsenal Sarandi Arsenal Sarandi", id: 459 },
  { country: "AR Argentina", name: "San Lorenzo San Lorenzo", id: 460 },
  { country: "AR Argentina", name: "San Martin S.J. San Martin S.J.", id: 461 },
  { country: "AR Argentina", name: "Agropecuario Agropecuario", id: 462 },
  { country: "AR Argentina", name: "Aldosivi Aldosivi", id: 463 },
  { country: "AR Argentina", name: "All Boys All Boys", id: 464 },
  { country: "AR Argentina", name: "Atletico DE Rafaela", id: 465 },
  { country: "AR Argentina", name: "Atletico Mitre", id: 466 },
  { country: "AR Argentina", name: "Boca Unidos", id: 467 },
  { country: "AR Argentina", name: "Brown DE Adrogue", id: 468 },
  { country: "AR Argentina", name: "Deportivo Moron", id: 469 },
  { country: "AR Argentina", name: "Ferro Carril Oeste Ferro Carril Oeste", id: 470 },
  { country: "AR Argentina", name: "Flandria Flandria", id: 471 },
  { country: "AR Argentina", name: "Guillermo Brown Guillermo Brown", id: 472 },
  { country: "AR Argentina", name: "Independ. Rivadavia Independ. Rivadavia", id: 473 },
  { country: "AR Argentina", name: "Sarmiento Junin Sarmiento Junin", id: 474 },
  { country: "AR Argentina", name: "Santamarina Santamarina", id: 475 },
  { country: "AR Argentina", name: "Deportivo Riestra Deportivo Riestra", id: 476 },
  { country: "AR Argentina", name: "Estudiantes S.l. Estudiantes S.l.", id: 477 },
  { country: "AR Argentina", name: "Instituto Cordoba", id: 478 },
  { country: "AR Argentina", name: "Gimnasia Jujuy", id: 479 },
  { country: "AR Argentina", name: "Quilmes Quilmes", id: 480 },
  { country: "AR Argentina", name: "Villa Dalmine", id: 481 },
  { country: "AR Argentina", name: "Almagro", id: 482 },
  { country: "AR Argentina", name: "Los Andes", id: 483 },
  { country: "AR Argentina", name: "Nueva Chicago", id: 484 },
  { country: "AR Argentina", name: "San Martin Tucuman", id: 485 },
  { country: "AR Argentina", name: "Juventud Unida", id: 486 },
  { country: "IT Italy", name: "Lazio Lazio", id: 487 },
  { country: "IT Italy", name: "Sassuolo", id: 488 },
  { country: "IT Italy", name: "AC Milan", id: 489 },
  { country: "IT Italy", name: "Cagliari", id: 490 },
  { country: "IT Italy", name: "Chievo", id: 491 },
  { country: "IT Italy", name: "Napoli", id: 492 },
  { country: "IT Italy", name: "Spal Spal", id: 493 },
  { country: "IT Italy", name: "Udinese Udinese", id: 494 },
  { country: "IT Italy", name: "Genoa Genoa", id: 495 },
  { country: "IT Italy", name: "Juventus Juventus", id: 496 },
  { country: "IT Italy", name: "AS Roma AS Roma", id: 497 },
  { country: "IT Italy", name: "Sampdoria Sampdoria", id: 498 },
  { country: "IT Italy", name: "Atalanta Atalanta", id: 499 },
  { country: "IT Italy", name: "Bologna Bologna", id: 500 },
  { country: "IT Italy", name: "Crotone Crotone", id: 501 },
  { country: "IT Italy", name: "Fiorentina", id: 502 },
  { country: "IT Italy", name: "Torino", id: 503 },
  { country: "IT Italy", name: "Verona", id: 504 },
  { country: "IT Italy", name: "Inter", id: 505 },
  { country: "IT Italy", name: "Benevento", id: 506 },
  { country: "IT Italy", name: "Ascoli", id: 507 },
  { country: "IT Italy", name: "Bari", id: 508 },
  { country: "IT Italy", name: "Cesena", id: 509 },
  { country: "IT Italy", name: "Cittadella", id: 510 },
  { country: "IT Italy", name: "Empoli", id: 511 },
  { country: "IT Italy", name: "Frosinone", id: 512 },
  { country: "IT Italy", name: "Novara", id: 513 },
  { country: "IT Italy", name: "Salernitana", id: 514 },
  { country: "IT Italy", name: "Spezia", id: 515 },
  { country: "IT Italy", name: "Ternana", id: 516 },
  { country: "IT Italy", name: "Venezia", id: 517 },
  { country: "IT Italy", name: "Brescia Brescia", id: 518 },
  { country: "IT Italy", name: "Carpi Carpi", id: 519 },
  { country: "IT Italy", name: "Cremonese Cremonese", id: 520 },
  { country: "IT Italy", name: "Foggia Foggia", id: 521 },
  { country: "IT Italy", name: "Palermo Palermo", id: 522 },
  { country: "IT Italy", name: "Parma Parma", id: 523 },
  { country: "IT Italy", name: "Perugia", id: 524 },
  { country: "IT Italy", name: "Pescara", id: 525 },
  { country: "IT Italy", name: "PRO Vercelli", id: 526 },
  { country: "IT Italy", name: "Virtus Entella", id: 527 },
  { country: "IT Italy", name: "Avellino Avellino", id: 528 },
  { country: "ES Spain", name: "Barcelona Barcelona", id: 529 },
  { country: "ES Spain", name: "Atletico Madrid", id: 530 },
  { country: "ES Spain", name: "Athletic Club", id: 531 },
  { country: "ES Spain", name: "Valencia", id: 532 },
  { country: "ES Spain", name: "Villarreal Villarreal", id: 533 },
  { country: "ES Spain", name: "Las Palmas", id: 534 },
  { country: "ES Spain", name: "Malaga Malaga", id: 535 },
  { country: "ES Spain", name: "Sevilla", id: 536 },
  { country: "ES Spain", name: "Leganes Leganes", id: 537 },
  { country: "ES Spain", name: "Celta Vigo Celta Vigo", id: 538 },
  { country: "ES Spain", name: "Levante", id: 539 },
  { country: "ES Spain", name: "Espanyol Espanyol", id: 540 },
  { country: "ES Spain", name: "Real Madrid Real Madrid", id: 541 },
  { country: "ES Spain", name: "Alaves Alaves", id: 542 },
  { country: "ES Spain", name: "Real Betis Real Betis", id: 543 },
  { country: "ES Spain", name: "Deportivo La Coruna Deportivo La Coruna", id: 544 },
  { country: "ES Spain", name: "Eibar Eibar", id: 545 },
  { country: "ES Spain", name: "Getafe Getafe", id: 546 },
  { country: "ES Spain", name: "Girona Girona", id: 547 },
  { country: "ES Spain", name: "Real Sociedad Real Sociedad", id: 548 },
  { country: "TR Turkey", name: "Besiktas Besiktas", id: 549 },
  { country: "UA Ukraine", name: "Shakhtar Donetsk Shakhtar Donetsk", id: 550 },
  { country: "CH Switzerland", name: "FC Basel 1893 FC Basel 1893", id: 551 },
  { country: "SI Slovenia", name: "Maribor Maribor", id: 552 },
  { country: "GR Greece", name: "Olympiakos Piraeus Olympiakos Piraeus", id: 553 },
  { country: "BE Belgium", name: "Anderlecht Anderlecht", id: 554 },
  { country: "RU Russia", name: "CSKA Moscow CSKA Moscow", id: 555 },
  { country: "AZ Azerbaijan", name: "Qarabag Qarabag", id: 556 },
  { country: "Apoel", name: "Apoel", id: 557 },
  { country: "RU Russia", name: "Spartak Moscow Spartak Moscow", id: 558 },
  { country: "RO Romania", name: "FCSB FCSB", id: 559 },
  { country: "CZ Czech-Republic", name: "Slavia Praha Slavia Praha", id: 560 },
  { country: "HR Croatia", name: "HNK Rijeka HNK Rijeka", id: 561 },
  { country: "KZ Kazakhstan", name: "FC Astana FC Astana", id: 562 },
  { country: "IL Israel", name: "Hapoel Beer Sheva Hapoel Beer Sheva", id: 563 },
  { country: "TR Turkey", name: "Istanbul Basaksehir Istanbul Basaksehir", id: 564 },
  { country: "CH Switzerland", name: "BSC Young Boys BSC Young Boys", id: 565 },
  { country: "BG Bulgaria", name: "Ludogorets Ludogorets", id: 566 },
  { country: "CZ Czech-Republic", name: "Plzen Plzen", id: 567 },
  { country: "MD Moldova", name: "Sheriff Tiraspol Sheriff Tiraspol", id: 568 },
  { country: "BE Belgium", name: "Club Brugge KV Club Brugge KV", id: 569 },
  { country: "RO Romania", name: "Viitorul Constanta Viitorul Constanta", id: 570 },
  { country: "AT Austria", name: "Red Bull Salzburg Red Bull Salzburg", id: 571 },
  { country: "UA Ukraine", name: "Dynamo Kyiv Dynamo Kyiv", id: 572 },
  { country: "RS Serbia", name: "FK Partizan FK Partizan", id: 573 },
  { country: "MK Macedonia", name: "Vardar Skopje Vardar Skopje", id: 574 },
  { country: "GR Greece", name: "AEK Athens FC AEK Athens FC", id: 575 },
  { country: "HU Hungary", name: "Budapest Honved", id: 576 },
  { country: "Albania", name: "FK Kukesi", id: 577 },
  { country: "Luxembourg", name: "F91 Dudelange", id: 578 },
  { country: "Montenegro", name: "Buducnost Podgorica", id: 579 },
  { country: "Faroe-Islands", name: "Vikingur Gota", id: 580 },
  { country: "GE Georgia", name: "Samtredia", id: 581 },
  { country: "Armenia", name: "Alashkert", id: 582 },
  { country: "Northern-Ireland", name: "Linfield", id: 583 },
  { country: "Ireland", name: "Dundalk", id: 584 },
  { country: "MSK Zilina", name: "MSK Zilina", id: 585 },
  { country: "Lithuania", name: "FK Zalgiris Vilnius", id: 586 },
  { country: "FI Finland", name: "Mariehamn", id: 587 },
  { country: "Bosnia", name: "Zrinjski", id: 588 },
  { country: "LV Latvia", name: "Spartaks Jurmala Spartaks Jurmala", id: 589 },
  { country: "Hibernians FC", name: "Hibernians FC", id: 590 },
  { country: "Andorra", name: "FC Santa Coloma", id: 591 },
  { country: "SP La Fiorita", name: "SP La Fiorita", id: 592 },
  { country: "ES Spain", name: "Europa Fc", id: 593 },
  { country: "FC Infonet", name: "FC Infonet", id: 594 },
  { country: "Trepca 89", name: "Trepca 89", id: 595 },
  { country: "RU Russia", name: "Zenit", id: 596 },
  { country: "RU Russia", name: "Lokomotiv", id: 597 },
  { country: "RS Serbia", name: "FK Crvena Zvezda", id: 598 },
  { country: "UA Ukraine", name: "Zorya Luhansk", id: 599 },
  { country: "BE Belgium", name: "Zulte Waregem", id: 600 },
  { country: "AT Austria", name: "Austria Vienna", id: 601 }

];


        return teams;
    } catch (error) {
        console.error("Error occured while fetching teams: ", error);
        throw error;
    }
}